# Generated by Django 2.2 on 2019-04-21 14:11

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facedetection', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='embeddingsmodel',
            name='embedding',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(blank=True, null=True), size=None), size=None),
        ),
        migrations.AlterField(
            model_name='embeddingsmodel',
            name='full_name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
